### ISSUE TITLE
User required activation after import

### ISSUE THREAD

**Issue by YesThatAllen** [vindia/discourse_user_importer#2]
Testing this today, the user I created has to be manually approved.

The username was generated from his email address (nice) and he was put into the right groups, but the user account was grayed out in the admin list.

**Comment by vindia** [comment]
The greyed out name doesn't mean it has to be manually approved, but it does mean that the user has to activate their account. This is done by them logging in for the first time.

Technically I think you could set this by setting `user.active = true` but I would advise against this. Now you keep the option to filter unactivated users and send them a reminder e-mail or delete them at some point.

BTW: Check also the setting in Discourse (under _Settings > Users_) called `purge unactivated users grace period days`. I set this to a very high number (9999) so my unactivated users don't get purged "suddenly"

**Comment by YesThatAllen** [comment]
In our case, users know they are being added, and expect to get emails directly. 

I'll give the user.active = true a shot (but we have only 60 users in this batch, I can manually activate them if needed)

thank you!

As for 9999 days...  [I couldn't agree more](https://meta.discourse.org/t/new-signups-who-never-validate-email-deleted-after-7-days/22736)

**Comment by YesThatAllen** [comment]
Ran out to time to try `user.active = true`

however, the import worked fine once the .txt file was `chmod 666` (before then, the script was failing due to permissions issues on the source file.

**Comment by vindia** [comment]
Yeah I've read your posts on the Discourse forum, it seems like we have a very similar use case (which is not entirely supported or understood by the Discourse team, unfortunately).
